export const homeObjOne = {
    id: 'Vision',
    lightBg: true,
    lightText: false,
    lightDescription: false,
    topLine: 'Vision',
    headline: 'Lubricate the inefficient  process  of construction material trading.',
    description: 'As industry pioneers, our goal is to lead the market in construction material procurement and sourcing. We stand out by delivering the most cost-effective raw materials to both consumers and businesses, all while maintaining uncompromising quality and security against quantity theft. Our commitment is bolstered by cutting-edge in-house technology that complements our innovative products and services.',
    buttonLabel: 'Sign Up now',
    imgStart: false,
    img: require('../../images/1.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true
}

export const teamData = [{
    id: 'Team',
    lightBg: false,
    lightText: true,
    lightDescription: true,
    topLine: 'Our Team',
    headline: 'Mr. Priyam Shukla',
    designation: 'Co-Founder and CEO',
    description: ' Comes with incredible business acumen having two generations of experience in the industry.  ',
    buttonLabel: 'Connect',
    imgStart: true,
    img: require('../../images/2.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
    buttonAction: `window.open('mailto:priyam@NirmanEasy.in','blank')`,
},
{
    id: 'Team',
    lightBg: false,
    lightText: true,
    lightDescription: true,
    topLine: 'Our Team',
    headline: 'Mr. Amit Verma',
    designation: 'Co-Founder and CTO',
    description: ' Has extensive experience in the software industry. He graduated from IIT-Madras with a  master’s degree in computer science engineering.',
    buttonLabel: 'Connect',
    imgStart: false,
    img: require('../../images/2.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
    buttonAction: ()=>window.open('mailto:amit@NirmanEasy.in','blank'),
},
{
    id: 'Team',
    lightBg: false,
    lightText: true,
    lightDescription: true,
    topLine: 'Our Team',
    headline: 'Mr. Mohammad Ali',
    designation: 'Co-Founder and CPO',
    description: 'Has more than a decade of experience in client communication, requirement and leading product development.',
    buttonLabel: 'Connect',
    imgStart: false,
    img: require('../../images/2.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
    buttonAction: ()=>window.open('mailto:amit@NirmanEasy.in','blank'),
},
{
    id: 'Team',
    lightBg: false,
    lightText: true,
    lightDescription: true,
    topLine: 'Our Team',
    headline: 'Mr. Udit Mishra',
    designation: 'Co-Founder and COO',
    description: 'Has more than a decade of experience in client communication, requirement and leading product development.',
    buttonLabel: 'Connect',
    imgStart: false,
    img: require('../../images/2.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
    buttonAction: ()=>window.open('mailto:amit@NirmanEasy.in','blank'),
}
]

export const homeObjFour = {
    id: 'Career',
    lightBg: true,
    lightText: false,
    lightDescription: false,
    topLine: 'Career',
    headline: 'Hiring coming soon...',
    description: 'Job opening coming soon for techincal and non-technical positions. Keep visiting this section.',
    buttonLabel: 'or direct apply',
    imgStart: false,
    img: require('../../images/3.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true
}

export const homeObjFive = {
    id: 'Contact',
    lightBg: false,
    lightText: true,
    lightDescription: true,
    topLine: 'Contact Us',
    headline: 'Have any query?',
    description: 'Write mail to us at enquire@nirmaneasy.in',
    buttonLabel: 'or drop a message',
    imgStart: true,
    img: require('../../images/4.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false
}
